### ISSUE TITLE
how should we use it in mulitisite?

### ISSUE THREAD

**Issue by alexlii1971** [wp-kitten/extended-wp-reset#1]
Hello,

Since it is quite important to reset a site, I would like to ask you how to activate it.

does it support reset sub site or reset whole multisite please?

networkly activate it or only in subsite?

thanks, and have a nice day.

Alex

**Comment by wp-kitten** [comment]
Hi, Alex

Please see https://wordpress.org/support/topic/how-should-we-use-it-in-mulitisite/#post-10055912

Thank you and have a nice day!

**Comment by wp-kitten** [comment]
![single-site-reset](https://user-images.githubusercontent.com/9017321/37196284-e9671054-237e-11e8-8a12-8f8b7eff800d.png)
![network-reset](https://user-images.githubusercontent.com/9017321/37196285-e983b18c-237e-11e8-908c-314d73ca32d4.png)

**Comment by alexlii1971** [comment]
I see, very clear. Thanks a lot.

But what about if I want to reset the main site of multisite?

should I activate both WP Rest and Extend WP reset only on main site?

Thanks.

Alex

**Comment by alexlii1971** [comment]
Hello @wp-kitten 

Did you have a chance to reply to me how to only reset the main site?

The main is quite different with other subsite, since it is related to network dashboard. what do you think?

is there any special step for  the main site reset?

Thanks

Alex

**Comment by alexlii1971** [comment]
@wp-kitten,

Untill today, I tested extended-wp-reset.

And I was redirect to a error page upon extended-wp-reset activation, screenshot here:
http://prntscr.com/isquaa

I can not access any dashboard again including subsite dashboard untill rename extended-wp-reset by FTP.

my test process and environment for your reference.

1. activated wp-reset, no errors and Wp-reset menu will show up under tools menus on all of subsite.
2. activated extended-wp-reset, but  i will be redirected.

Wordpress 4.9.4, HHVM, Redis cache.

Thanks.

Ale
